parameters: {}
environment:
  MONGODB_USERNAME: ${MONGODB_USERNAME}
  MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  MONGODB_HOST: ${MONGODB_HOST}
  OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
  TOGGL_TRACK_API_KEY: ${TOGGL_TRACK_API_KEY}
  TODOIST_API_KEY: ${TODOIST_API_KEY}
  GITHUB_USERNAME: ${GITHUB_USERNAME}
  GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
packages:
  # - name: "savedata15m"
  #   functions:
  #     - name: "fn15m"
  #       runtime: "python:default"
  #       triggers:
  #         - name: "every15m"
  #           sourceType: scheduler
  #           sourceDetails:
  #             cron: "0,15,30,45 * * * *" # every 15 minutes
  #       # limits:
  #       #   timeout: 180000
  - name: "savedata0300h"
    functions:
      - name: "fn0300h"
        runtime: "python:default"
        triggers:
          - name: "every0300h"
            sourceType: scheduler
            sourceDetails:
              cron: "0 3 * * *" # every day at 03:00 AM
        limits:
          timeout: 180000
  # - name: "savedata3d"
  #   functions:
  #     - name: "fn3d"
  #       runtime: "python:default"
  #       main: "main.py"
  #       triggers:
  #         - name: "every3d"
  #           sourceType: scheduler
  #           sourceDetails:
  #             cron: "0 3 */3 * *" # every 3 days at 03:00 AM
  #       limits:
  #         timeout: 180000
  # binary: false
  # main: ""
  # web: true
  # websecure: false
  # parameters: {}
  # environment: {}
  # annotations: {}
  # limits: {}
