alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
functions:
  - github:
      branch: main
      deploy_on_push: true
      repo: jskherman/do_savefunction
    name: savedata
    routes:
      - path: /
    source_dir: /
name: savedata
